### ISSUE TITLE
there is a issue when  my obsession work with loadview

### ISSUE THREAD

**Issue by shusoar** [tpope/vim-obsession#22]
i run vim in ubuntu
in my ~/.vimrc i set
```
set sessionoptions-=options
set viewoptions=folds,cursor,unix,slash

augroup autosave_buffer
 autocmd!
 autocmd BufWinLeave *.* mkview
 autocmd BufWinEnter *.* silent loadview
augroup END
```
then i open a file say **test.c** with fold --> :Obsession  -->close vim
 --> **vim text.c**   open this file and expand some fold & add some line-->close vim -->**vim -S Session.vim** open the session.
then there is some error messages display in my terminal

**Comment by tpope** [comment]
"Some error messages" is not helpful.

**Comment by shusoar** [comment]
reinstall the latest vim-obsession i fixed it :-)
