### ISSUE TITLE
Tab name

### ISSUE THREAD

**Issue by deshtop** [tpope/vim-obsession#23]
Hi, i'm using [taboo](https://github.com/gcmt/taboo.vim) to set tab names in a vim session, which aren't restored with obsession. Is it possible to add this feature?
Thanks!

**Comment by tpope** [comment]
It would be on taboo to find a way to persist tab names in the session. I'd provide any necessary hooks, if you figure out what those hooks would be.

**Comment by deshtop** [comment]
For reference: [storing tab titles already works](https://github.com/gcmt/taboo.vim/issues/9).
