### ISSUE TITLE
Persist NetRW/vim-vinegar splits?

### ISSUE THREAD

**Issue by cvincent** [tpope/vim-obsession#27]
Not sure if I'm missing an option, but I did get my sessions working exactly how I'd like them so far, except that NetRW/vim-vinegar splits are not persisted. This is certainly doesn't break my workflow, but wanted to make sure you were aware of it or see if there's just an option I need to include.

**Comment by tpope** [comment]
They're persisted for me.

**Comment by foxt451** [comment]
netrw doesn't get persisted for me as well, just a blank screen (not sure if OP meant this here). 
Here is my relevant .vimrc parts:
```
set sessionoptions+=buffers
let g:netrw_liststyle=3
```

I use vinegar too
