### ISSUE TITLE
Passing Args to `Obsess` Not Working

### ISSUE THREAD

**Issue by civiclabsconsulting** [tpope/vim-obsession#30]
First off, great plugin. Nice work @tpope! Second, I'm having trouble passing args to the `Obsess` function (in the event that I need to create a new session with a custom file name).

Is this something to do with `vim-obsession`, or something else on my end I can fix?

```
" Obsession {
nmap <Leader>s :call ToggleObsess()<CR>

function! ToggleObsess()
    let d=FindRootDirectory()."/.session.vim"
    if !empty(glob(d))
        " Load previous session
        source d
    else
        " Create new session
        Obsess d
    endif
endfunction
" }
```

Much appreciated, 

Brandon

**Comment by tpope** [comment]
```
exe 'Obsess' fnameescape(d)
```
