### ISSUE TITLE
Windows switch slowdown

### ISSUE THREAD

**Issue by oblitum** [tpope/vim-obsession#40]
Depending on IO speed (like a slow disk or inside Windows Subsystem for Linux), Obsession will cause slowdown when switching between windows, because it hits files every time buffers change, it can be quite perceptible, the editor blocking while simply moving window focus. Maybe using async would solve the matter.

**Comment by oblitum** [comment]
Since then, I've discovered that it was the cause of slowness with other buffer related operations too, affecting fzf.vim and goyo.vim for example. I just removed it from `BufEnter`, leaving it on `VimLeavePre` solely.

**Comment by tpope** [comment]
Yeah, `BufEnter` is a terribly spammy autocommand I've only used as a last resort. I've added an option to turn it off.

**Comment by oblitum** [comment]
Thanks.

**Comment by oblitum** [comment]
Nice for `g:obsession_no_bufenter` but `g:obsession_append` is for what?
