### ISSUE TITLE
Buffers seem to be overflowing to session files when no sessions is open

### ISSUE THREAD

**Issue by slackhead** [tpope/vim-obsession#42]
If I open a file when obsession isn't running (at least according to my airline status). The next session I load (using -S) it will load the last buffer I had open and add it to the session.

Is there a way around this?

**Comment by slackhead** [comment]
Ok I've just made a small test:

touch a b
vim a
:Obsession a-test
:q 

vim b
:Obsession b-test
:q 

vim -S a-test

It contains a buffer with 'a'. How? Why? What can I do to avoid leakiing from session to session like that?

**Comment by tpope** [comment]
That *is* weird. The most obvious thing to suggest is turning off `'viminfo'` and seeing if the problem persists.

**Comment by slackhead** [comment]
Yes, that fixes it. Thanks.

I was using %50 which loads previous buffers. There's no need to use this since I'm using session files, so I've just reverted to the default setting.
