### ISSUE TITLE
Documentation of command not correct?

### ISSUE THREAD

**Issue by jamatsui** [tpope/vim-obsession#49]
Documentation says: 

> Use :Obsess (with optional file/directory name) to start recording to a session file and :Obsess! to stop and throw it away. That's it. Load a session in the usual manner: vim -S, or :source it.

But as far as I can tell the command is :Obsession and :Obsession!

Digging this plugin, thanks for sharing!

**Comment by tpope** [comment]
It's a deliberate bit of whimsy as Vim allows you to abbreviate any command as long as it's unambiguous.

**Comment by jamatsui** [comment]
good to know. Thanks!
