### ISSUE TITLE
NERD Tree isn't restored properly

### ISSUE THREAD

**Issue by jondkinney** [tpope/vim-obsession#5]
This isn't a deal breaker, but if I have NERD Tree open in the main window or another vim tab and then quit out of vim and re-open that session, the split that had NERD Tree in it is just blank. It's easy enough to just close that split and then re-open NERD Tree, but I just thought I'd see if you have any idea if it's possible to actually restore it fully?

If there isn't a way to restore NERD Tree properly, is there a way to close out all the NERD Tree splits automatically when quitting vim perhaps? Maybe that isn't good either, just throwing ideas out.

Thanks much

**Comment by Iambecomeroot** [comment]
An acceptable solution for me would just be to ignore nerd tree when saving. Is this possible?

**Comment by tpope** [comment]
@Iambecomeroot `set sessionoptions-=blank` appears to do exactly that, and it's now the default in obsession.vim.
