### ISSUE TITLE
Suggestion: rename Session.vim to .session.vim

### ISSUE THREAD

**Issue by jamatsui** [tpope/vim-obsession#50]
Hi Tim,

Was wondering if it would make more sense to change the generic filename to .session.vim instead of Session.vim. I realize there's a way to customize the filename for myself, but was thinking this could be applied more generically with the plugin and is more in-line with dot file convention. Thanks for this plugin.

**Comment by tpope** [comment]
The filename is ugly but it's the default for `vim -S` so it's the only option in my book.

**Comment by jamatsui** [comment]
Hah, makes sense! Thanks
