### ISSUE TITLE
Persist wildignore across sessions

### ISSUE THREAD

**Issue by robertjk** [tpope/vim-obsession#53]
Is there a way to persist `wildignore` option value throught sessions? I set this one per-project and would like to have it set properly after I load a session for a given project.

I know you've disabled saving options in your plugin, but I wonder if there is another (suggested) way of doing that?

**Comment by tpope** [comment]
You could manually rig something up to copy the value of `&wildignore` to from and to `g:UPPERCASE_VARIABLE` on startup and exit. Afraid I don't have much more to offer than that.

**Comment by robertjk** [comment]
Okay, thanks for the feedback. At least I know what's the situation.
