### ISSUE TITLE
Weird error messages never happened before

### ISSUE THREAD

**Issue by markwu** [tpope/vim-obsession#59]
Weird error messages never happened before.

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing BufEnter Autocommands for "*":
Vim(mksession):E11: Invalid in command-line window; <CR> executes, CTRL-C quits: mksession! /Users/mark/.vim/sessions/\%Users\%mark\%.dot_vim.vim
Press ENTER or type command to continue
```

## reproduce steps ##
1. vim -u NONE
2. `q:` to open command line window
3. type `:mksession` to make a session

## my platform ##
macOS 10.14.6
head version of vim, neovim, macvim

**Comment by markwu** [comment]
It seems I have to disable `s:persist()` when enter buffer with

```
let g:obsession_no_bufenter = 1
```

**Comment by markwu** [comment]
Seems no way to identify command line window, I just use try-catch to avoid those error messages.

```vim
  autocmd BufEnter *
        \ if !get(g:, 'obsession_no_bufenter') |
        \   try |
        \     exe s:persist() |
        \   catch |
        \   endtry |
        \ endif
```

**Comment by mvanderkamp** [comment]
I'm not sure that's a good idea to just silence the error message- it looks like the whole autocommand is disabled, and we stop obsessing.

**Comment by mvanderkamp** [comment]
Might be able to do something with `CmdWinLeave` though. Perhaps use `silent` as above but then register the autocmd again on CmdWinLeave, if we identified that we encountered the error?

**Comment by mvanderkamp** [comment]
Or could just do a good old try-catch block

**Comment by mvanderkamp** [comment]
Deleted my comments since I'm a dolt- silent! should work fine.

**Comment by markwu** [comment]
I tested it, but still get the same error messages.

**Comment by tpope** [comment]
I thought I tested it too but I guess not. Looks like `'buftype'` hasn't been set yet. God, why is this so stupid.

**Comment by markwu** [comment]
Thanks, I confirmed it fixed.
