### ISSUE TITLE
Obsession on bufenter creates a poor fireplace experience

### ISSUE THREAD

**Issue by benknoble** [tpope/vim-obsession#60]
The `cq` maps from tpope/vim-fireplace create Scratch windows. Without disabling Obsession on BufEnter, these buffers trigger Obsession's `mksession`, and chaos ensues. The `cq` mappings will stop working, and you'll get `E95` a lot.

The fix is using the `g:obsession_no_bufenter` variable, but it would be nice to perhaps skip certain buffers like the command line window.

**Comment by tpope** [comment]
Solved in #59 unless I'm missing something?

**Comment by benknoble** [comment]
You're not; I didn't upgrade. Thanks
