### ISSUE TITLE
Fileencoding override is not preserved

### ISSUE THREAD

**Issue by L1Q** [tpope/vim-obsession#64]
Sometimes I have to reload a buffer with ``:e ++enc=cp1251 ++ff=dos``. This allows me to see and write cyrillic characters correctly.
After session reloading however the encoding is reset and the aforementioned command has to be run again.

Related vim doc:
http://vimdoc.sourceforge.net/htmldoc/editing.html#++enc

This is likely a vim issue and not obsession issue, expecting workarounds and plugin suggestions.

**Comment by tpope** [comment]
Yeah, sounds like a Vim issue. Doing `:set sessionoptions+=localoptions` _might_ help by storing `'enc'` and `'ff'` in the session. I'll let you test.

**Comment by L1Q** [comment]
``sessionoptions`` does not seem to help.
