### ISSUE TITLE
Can you provide a ignore list?

### ISSUE THREAD

**Issue by nyngwang** [tpope/vim-obsession#70]
As title. I'm using a neovim plugin called `nvim-tree.lua` and it seems that this plugin also records the file-tree into the session. When I restore the session with `nvim -S` the file-tree also opened as a buffer while I don't want this to happen. As shown below, the `intro/` buffer should not appear:

<img src="https://user-images.githubusercontent.com/24765272/145855055-0ef33c91-de09-41fe-a991-b3dafd68f646.png" width="500">

**Comment by tpope** [comment]
When I try it, nvim-tree buffers are given `buftype=nofile`, which causes Vim to skip recording them in the session. This is with a config of `require('nvim-tree').setup()`. I leave it to you to determine why your setup differs.

**Comment by skwee357** [comment]
Hey. Sorry for bringing this up again, but I have the same issue. Apparently, `nvim-tree` file type is `NvimTree` and not `nofile` hence it get's restored when I call `nvim -S Session.vim`. Appreciate some guidance if possible. Thanks!

**Comment by skwee357** [comment]
Yes you are right, my bad. The `buftype` is indeed `nofile`, but even with the basic config of `nvim-tree`, it's still being monitored by the session

**Comment by tpope** [comment]
[`:mksession` skips `nofile` buffers unless `'sessionoptions'` contains `blank`](https://github.com/neovim/neovim/blob/d367ed9b23d481998d297d812f54b950e5511c24/src/nvim/ex_session.c#L189-L193). And [Obsession always removes `blank` from `'sessionoptions'](https://github.com/tpope/vim-obsession/blob/7d39576149d17bde3c096fd57e3a2cdae65deaf5/plugin/obsession.vim#L73) before calling `:mkession`.
