### ISSUE TITLE
When vim is closed unexpectedly, the session won't remember its buffers ever again

### ISSUE THREAD

**Issue by Zeioth** [tpope/vim-obsession#71]
The way to fix this is to create the session again with 

    :Obsession ~/path/file.vim

Now I have an UPS so hopefuly it should't happen that often.

**Comment by augustobmoura** [comment]
Hit the same issue, removing the Session.vim file and creating it again also works

**Comment by norogoth** [comment]
This has been happening to me too. When I close tmux and restart all my sessions are now overridden. Makes Obsession to dangerous for me to use at the moment.

**Comment by tpope** [comment]
Alright fine I took a blind stab at a fix.

**Comment by norogoth** [comment]
Cool. Thanks @tpope How do I update? Do I only need to run `:PlugInstall` ?

**Comment by tpope** [comment]
I don't know, how every your plugin manager works. If you tried and failed, it's probably because you did it in the 2 minutes before I pushed.

**Comment by Zeioth** [comment]
Thank you pope, I just noticed the PR, testing it.

**Comment by norogoth** [comment]
Haven't run into the issue yet! LGTM!
