### ISSUE TITLE
Windows are not balanced after re-opening a session

### ISSUE THREAD

**Issue by ariel-frischer** [tpope/vim-obsession#75]
I always gotta hit it with a `ctrl+w` -> `=` to balance my windows. Is there a way I can call this after loading in my session automatically? Is there a session configuration option that fixes this?

**Comment by tpope** [comment]
Do you have `'equalalways'` enabled? I do, and it seems to apply after loading the session.

You could always force it with `autocmd SessionLoadPost * wincmd =`.
