### ISSUE TITLE
Toggle obsession also with filename

### ISSUE THREAD

**Issue by BeTmAsTeR** [tpope/vim-obsession#77]
Right now it's possible to toggle the recording of a session only with the command `Obesssion` **with no parameter**, allowing to start and stop the tracking with the exact same command (really useful because i only need one mapping)

But if i want to save the session file with a different name i need two different commands, one with the filename to start the tracking and one without to stop it
`Obsession .session.vim` -> Start tracking
`Obesssion` -> Stop tracking

Wouldn't it make more sense to allow the toggling of the tracking with the exact same command also when a filename is specified?
`Obsession .session.vim` -> Toggle the tracking

**Comment by tpope** [comment]
I think it would be confusing if `:Obsession myfile.vim` _didn't_ start writing the session `myfile.vim`. If you want to rig up a toggle map, I imagine you could achieve it by fiddling with the internal variable `g:this_obsession`. Just make sure it's an absolute path.
